## Web scraping de IMDB

Descarga la información correspondiente y guarda en un csv el top de las 250 películas mediante webscraping. Encapsúlalo en un script.

Obtén:
* Título
* Año
* Duración
* Posición
* Rating

In [ ]:
import cloudscraper     # de momento funciona para que Cloudfare no nos bloquee
from bs4 import BeautifulSoup

scraper = cloudscraper.create_scraper(
    browser={
        'browser': 'chrome',
        'platform': 'android',
        'desktop': False
    }
)
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}

html = scraper.get("https://www.filmaffinity.com/es/countcat.php?id=new_hbo_es")

soup = BeautifulSoup(html.text, "html.parser")
print(soup.title)

<title>HBO Max España - FilmAffinity</title>

In [4]:
soup = BeautifulSoup(html.text, "html.parser")
# top 25
soup

<!DOCTYPE html>

<html lang="es">
<head>
<title>HBO Max España - FilmAffinity</title>
<meta charset="utf-8"/>
<meta content="Películas y series de HBO Max España ordenadas por número de votos" name="description"/>
<meta content="FilmAffinity" property="og:site_name"/>
<meta content="website" property="og:type"/>
<meta content="https%3A%2F%2Fwww.filmaffinity.com%2Fes%2Fcountcat.php%3Fid%3Dnew_hbo_es" property="og:url"/>
<meta content="HBO Max España" property="og:title"/>
<meta content="Películas y series de HBO Max España ordenadas por número de votos" property="og:description"/>
<meta content="https://filmaffinity.com/images/icon.png" property="og:image">
<meta content="@Filmaffinity" name="twitter:site"/>
<meta content="summary" name="twitter:card"/>
<meta content="HBO Max España" name="twitter:title"/>
<meta content="Películas y series de HBO Max España ordenadas por número de votos" name="twitter:description"/>
<meta content="https://filmaffinity.com/images/icon.png" name="twitter:image"/>
<link href="https://www.filmaffinity.com/es/countcat.php?id=new_hbo_es" rel="canonical"/>
<link href="/favicon.png" rel="icon" type="image/png"/>
<link href="/style/bootstrap/fa-theme.5.3.2.1774355070.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/swiper/swiper-bundle.min.1706000643.css" rel="stylesheet" type="text/css"/>
<link href="/style/bootstrap/fa-categories.min.1770110985.css" rel="stylesheet" type="text/css"/>
<link href="/style/main3.1773834909.css" rel="stylesheet" type="text/css"/>
<link href="/style/moviecards3.1719569557.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/slick/slick.1651839967.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/slick/slick-theme.1740125949.css" rel="stylesheet" type="text/css"/>
<link href="/style/all.min.1731580891.css" rel="stylesheet" type="text/css"/>
<link href="/style/fa-icons.1676894187.css" rel="stylesheet" type="text/css"/>
<link href="/style/magic-check.min.1539096291.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/new-autocomplete/fa-autocomplete.1757321028.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/autocomplete/easy-autocomplete.min.1585727670.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/autocomplete/easy-autocomplete.themes.min.1585727670.css" rel="stylesheet" type="text/css"/>
<script src="/js/local_es.1539096293.js"></script>
<script src="/js/jquery/jquery-3.7.1.min.1769585555.js"></script>
<script src="/js/bootstrap/bootstrap.bundle.min.5.3.2.1694701167.js"></script>
<script src="/js/jquery/plugin/swiper/swiper-bundle.min.1706000662.js"></script>
<script src="/js/fa-swiper.class.1749625520.js"></script>
<script src="/js/categories.1762945103.js"></script>
<script src="/js/fa-lightbox.class.1740472996.js"></script>
<script src="/js/jquery/plugin/slick/slick.min.1651839936.js"></script>
<script src="/js/jquery/plugin/dompurify/purify.min.1737551546.js"></script>
<script src="/js/crc32.1539096293.js"></script>
<script src="/js/translate-context.1539096293.js"></script>
<script src="/js/locale/texts-es_ES.1772190748.js"></script>
<script src="/js/jquery/plugin/jquery.cookie.1539096308.js"></script>
<script src="/js/ads.1539096293.js"></script>
<script src="/js/main.1772010524.js"></script>
<script src="/js/pagetop.1668696477.js"></script>
<script src="/js/nav.class.1739967269.js"></script>
<script src="/js/z-index-fix.1773836800.js"></script>
<script src="/js/jquery/plugin/lazysizes/lazysizes.min.1602068375.js"></script>
<script src="/js/fa-lists-tip.1770898183.js"></script>
<script src="/js/jquery/plugin/new-autocomplete/fa-autocomplete2.1770723602.js"></script>
<script src="/js/jquery/plugin/autocomplete/jquery.easy-autocomplete.1671723118.js"></script>
<script src="/js/bootstrap/bootstrap-autocomplete.1706000471.js"></script>
<link href="https://www.filmaffinity.com/es/countcat.php?id=new_hbo_es" hreflang="es" rel="alternate"/>
<link href="https://www.filmaffinity.com/en/countcat.php?id=new_hbo_es" hreflang="en" rel="alternate"/>
<link href="https://www.filmaffinity.com/mx/countcat.php?id=new_hbo_es" hreflang="es-MX" rel="alternate"/>
<link href="https://www.filmaffinity.com/ar/countcat.php?id=new_hbo_es" hreflang="es-AR" rel="alternate"/>
<link href="https://www.filmaffinity.com/cl/countcat.php?id=new_hbo_es" hreflang="es-CL" rel="alternate"/>
<link href="https://www.filmaffinity.com/co/countcat.php?id=new_hbo_es" hreflang="es-CO" rel="alternate"/>
<link href="https://www.filmaffinity.com/uy/countcat.php?id=new_hbo_es" hreflang="es-UY" rel="alternate"/>
<link href="https://www.filmaffinity.com/py/countcat.php?id=new_hbo_es" hreflang="es-PY" rel="alternate"/>
<link href="https://www.filmaffinity.com/pe/countcat.php?id=new_hbo_es" hreflang="es-PE" rel="alternate"/>
<link href="https://www.filmaffinity.com/ec/countcat.php?id=new_hbo_es" hreflang="es-EC" rel="alternate"/>
<link href="https://www.filmaffinity.com/ve/countcat.php?id=new_hbo_es" hreflang="es-VE" rel="alternate"/>
<link href="https://www.filmaffinity.com/cr/countcat.php?id=new_hbo_es" hreflang="es-CR" rel="alternate"/>
<link href="https://www.filmaffinity.com/hn/countcat.php?id=new_hbo_es" hreflang="es-HN" rel="alternate"/>
<link href="https://www.filmaffinity.com/gt/countcat.php?id=new_hbo_es" hreflang="es-GT" rel="alternate"/>
<link href="https://www.filmaffinity.com/bo/countcat.php?id=new_hbo_es" hreflang="es-BO" rel="alternate"/>
<link href="https://www.filmaffinity.com/do/countcat.php?id=new_hbo_es" hreflang="es-DO" rel="alternate"/>
<link href="https://www.filmaffinity.com/us/countcat.php?id=new_hbo_es" hreflang="en-US" rel="alternate"/>
<link href="https://www.filmaffinity.com/uk/countcat.php?id=new_hbo_es" hreflang="en-GB" rel="alternate"/>
<link href="https://www.filmaffinity.com/ie/countcat.php?id=new_hbo_es" hreflang="en-IE" rel="alternate"/>
<link href="https://www.filmaffinity.com/au/countcat.php?id=new_hbo_es" hreflang="en-AU" rel="alternate"/>
<link href="https://www.filmaffinity.com/ca/countcat.php?id=new_hbo_es" hreflang="en-CA" rel="alternate"/>
<!-- InMobi Choice. Consent Manager Tag v3.0 (for TCF 2.2) -->
<script>
(function() {
  var host = window.location.hostname;
  var element = document.createElement('script');
  var firstScript = document.getElementsByTagName('script')[0];
  var url = 'https://cmp.inmobi.com'
    .concat('/choice/', 'LBBrF-bdAtkuF', '/', host, '/choice.js?tag_version=V3');
  var uspTries = 0;
  var uspTriesLimit = 3;
  element.async = true;
  element.type = 'text/javascript';
  element.src = url;

  firstScript.parentNode.insertBefore(element, firstScript);

  function makeStub() {
    var TCF_LOCATOR_NAME = '__tcfapiLocator';
    var queue = [];
    var win = window;
    var cmpFrame;

    function addFrame() {
      var doc = win.document;
      var otherCMP = !!(win.frames[TCF_LOCATOR_NAME]);

      if (!otherCMP) {
        if (doc.body) {
          var iframe = doc.createElement('iframe');

          iframe.style.cssText = 'display:none';
          iframe.name = TCF_LOCATOR_NAME;
          doc.body.appendChild(iframe);
        } else {
          setTimeout(addFrame, 5);
        }
      }
      return !otherCMP;
    }

    function tcfAPIHandler() {
      var gdprApplies;
      var args = arguments;

      if (!args.length) {
        return queue;
      } else if (args[0] === 'setGdprApplies') {
        if (
          args.length > 3 &&
          args[2] === 2 &&
          typeof args[3] === 'boolean'
        ) {
          gdprApplies = args[3];
          if (typeof args[2] === 'function') {
            args[2]('set', true);
          }
        }
      } else if (args[0] === 'ping') {
        var retr = {
          gdprApplies: gdprApplies,
          cmpLoaded: false,
          cmpStatus: 'stub'
        };

        if (typeof args[2] === 'function') {
          args[2](retr);
        }
      } else {
        if(args[0] === 'init' && typeof args[3] === 'object') {
          args[3] = Object.assign(args[3], { tag_version: 'V3' });
        }
        queue.push(args);
      }
    }

    function postMessageEventHandler(event) {
      var msgIsString = typeof event.data === 'string';
      var json = {};

      try {
        if (msgIsString) {
          json = JSON.parse(event.data);
        } else {
          json = event.data;
        }
      } catch (ignore) {}

      var payload = json.__tcfapiCall;

      if (payload) {
        window.__tcfapi(
          payload.command,
          payload.version,
          function(retValue, success) {
            var returnMsg = {
              __tcfapiReturn: {
                returnValue: retValue,
                success: success,
                callId: payload.callId
              }
            };
            if (msgIsString) {
              returnMsg = JSON.stringify(returnMsg);
            }
            if (event && event.source && event.source.postMessage) {
              event.source.postMessage(returnMsg, '*');
            }
          },
          payload.parameter
        );
      }
    }

    while (win) {
      try {
        if (win.frames[TCF_LOCATOR_NAME]) {
          cmpFrame = win;
          break;
        }
      } catch (ignore) {}

      if (win === window.top) {
        break;
      }
      win = win.parent;
    }
    if (!cmpFrame) {
      addFrame();
      win.__tcfapi = tcfAPIHandler;
      win.addEventListener('message', postMessageEventHandler, false);
    }
  };

  makeStub();

  function makeGppStub() {
    const CMP_ID = 10;
    const SUPPORTED_APIS = [
      '2:tcfeuv2',
      '6:uspv1',
      '7:usnatv1',
      '8:usca',
      '9:usvav1',
      '10:uscov1',
      '11:usutv1',
      '12:usctv1'
    ];

    window.__gpp_addFrame = function (n) {
      if (!window.frames[n]) {
        if (document.body) {
          var i = document.createElement("iframe");
          i.style.cssText = "display:none";
          i.name = n;
          document.body.appendChild(i);
        } else {
          window.setTimeout(window.__gpp_addFrame, 10, n);
        }
      }
    };
    window.__gpp_stub = function () {
      var b = arguments;
      __gpp.queue = __gpp.queue || [];
      __gpp.events = __gpp.events || [];

      if (!b.length || (b.length == 1 && b[0] == "queue")) {
        return __gpp.queue;
      }

      if (b.length == 1 && b[0] == "events") {
        return __gpp.events;
      }

      var cmd = b[0];
      var clb = b.length > 1 ? b[1] : null;
      var par = b.length > 2 ? b[2] : null;
      if (cmd === "ping") {
        clb(
          {
            gppVersion: "1.1", // must be “Version.Subversion”, current: “1.1”
            cmpStatus: "stub", // possible values: stub, loading, loaded, error
            cmpDisplayStatus: "hidden", // possible values: hidden, visible, disabled
            signalStatus: "not ready", // possible values: not ready, ready
            supportedAPIs: SUPPORTED_APIS, // list of supported APIs
            cmpId: CMP_ID, // IAB assigned CMP ID, may be 0 during stub/loading
            sectionList: [],
            applicableSections: [-1],
            gppString: "",
            parsedSections: {},
          },
          true
        );
      } else if (cmd === "addEventListener") {
        if (!("lastId" in __gpp)) {
          __gpp.lastId = 0;
        }
        __gpp.lastId++;
        var lnr = __gpp.lastId;
        __gpp.events.push({
          id: lnr,
          callback: clb,
          parameter: par,
        });
        clb(
          {
            eventName: "listenerRegistered",
            listenerId: lnr, // Registered ID of the listener
            data: true, // positive signal
            pingData: {
              gppVersion: "1.1", // must be “Version.Subversion”, current: “1.1”
              cmpStatus: "stub", // possible values: stub, loading, loaded, error
              cmpDisplayStatus: "hidden", // possible values: hidden, visible, disabled
              signalStatus: "not ready", // possible values: not ready, ready
              supportedAPIs: SUPPORTED_APIS, // list of supported APIs
              cmpId: CMP_ID, // list of supported APIs
              sectionList: [],
              applicableSections: [-1],
              gppString: "",
              parsedSections: {},
            },
          },
          true
        );
      } else if (cmd === "removeEventListener") {
        var success = false;
        for (var i = 0; i < __gpp.events.length; i++) {
          if (__gpp.events[i].id == par) {
            __gpp.events.splice(i, 1);
            success = true;
            break;
          }
        }
        clb(
          {
            eventName: "listenerRemoved",
            listenerId: par, // Registered ID of the listener
            data: success, // status info
            pingData: {
              gppVersion: "1.1", // must be “Version.Subversion”, current: “1.1”
              cmpStatus: "stub", // possible values: stub, loading, loaded, error
              cmpDisplayStatus: "hidden", // possible values: hidden, visible, disabled
              signalStatus: "not ready", // possible values: not ready, ready
              supportedAPIs: SUPPORTED_APIS, // list of supported APIs
              cmpId: CMP_ID, // CMP ID
              sectionList: [],
              applicableSections: [-1],
              gppString: "",
              parsedSections: {},
            },
          },
          true
        );
      } else if (cmd === "hasSection") {
        clb(false, true);
      } else if (cmd === "getSection" || cmd === "getField") {
        clb(null, true);
      }
      //queue all other commands
      else {
        __gpp.queue.push([].slice.apply(b));
      }
    };
    window.__gpp_msghandler = function (event) {
      var msgIsString = typeof event.data === "string";
      try {
        var json = msgIsString ? JSON.parse(event.data) : event.data;
      } catch (e) {
        var json = null;
      }
      if (typeof json === "object" && json !== null && "__gppCall" in json) {
        var i = json.__gppCall;
        window.__gpp(
          i.command,
          function (retValue, success) {
            var returnMsg = {
              __gppReturn: {
                returnValue: retValue,
                success: success,
                callId: i.callId,
              },
            };
            event.source.postMessage(msgIsString ? JSON.stringify(returnMsg) : returnMsg, "*");
          },
          "parameter" in i ? i.parameter : null,
          "version" in i ? i.version : "1.1"
        );
      }
    };
    if (!("__gpp" in window) || typeof window.__gpp !== "function") {
      window.__gpp = window.__gpp_stub;
      window.addEventListener("message", window.__gpp_msghandler, false);
      window.__gpp_addFrame("__gppLocator");
    }
  };

  makeGppStub();

  var uspStubFunction = function() {
    var arg = arguments;
    if (typeof window.__uspapi !== uspStubFunction) {
      setTimeout(function() {
        if (typeof window.__uspapi !== 'undefined') {
          window.__uspapi.apply(window.__uspapi, arg);
        }
      }, 500);
    }
  };

  var checkIfUspIsReady = function() {
    uspTries++;
    if (window.__uspapi === uspStubFunction && uspTries < uspTriesLimit) {
      console.warn('USP is not accessible');
    } else {
      clearInterval(uspInterval);
    }
  };

  if (typeof window.__uspapi === 'undefined') {
    window.__uspapi = uspStubFunction;
    var uspInterval = setInterval(checkIfUspIsReady, 6000);
  }
})();
</script>
<!-- End InMobi Choice. Consent Manager Tag v3.0 (for TCF 2.2) --> <script>
        $(function(){
            sessPing("0169c3d8cd13551028f6a38eea3d4b97e8bc5d410c", 2400);
            var tcTexts = TranslateContext.getInstance(commonTextsJs);
        });
    </script>
<script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
<script>

        var googletag = googletag || {};

        googletag.cmd = googletag.cmd || [];

 </script>
<script src="https://sc-devel.s3.eu-central-1.amazonaws.com/Skins/SMCService.js"></script>
<script src="https://sc-devel.s3.eu-central-1.amazonaws.com/sc-tagmanager/filmaffinity.js"></script>
<script async="async" src="https://cdn.smartclip-services.com/v1/Storage-a482323/smartclip-services/HeaderBidding/js/SmartclipConfig.js"></script>
<script>
  var sc = document.createElement ("script")
  sc.src="https://cdn.smartclip-services.com/v1/Storage-a482323/smartclip-services/wrappers/sc__sync.js"
  sc.onload = function(){
  __sc__sync(["e40c3a8c-532f-469b-8e2a-1cc44f47c967"]) // id de la zona
  }
  document.head.appendChild(sc)
</script><script>$(function(){sendpv("97db336c6e10c8b8646054e735f39753");});</script>
</meta></head>
<body>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-TZX5NYMKZC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-TZX5NYMKZC');
</script>
<header id="page-header">
<div id="header-top">
<div class="cpanel top-wrapper">
<div id="logo-container">
<a href="https://www.filmaffinity.com/es/main.html">
<img alt="logo" src="/images/logo4.png"/>
<div class="logo-siteloc">España</div>
</a>
</div><!-- logo-container -->
<div class="search-box">
<div class="s-large" id="topsearch-ac">
<form accept-charset="UTF-8" action="https://www.filmaffinity.com/es/search.php" data-ftoken="01b860d3596af6ffe677117fbe9dd62782cd86cfcde1e9d8d7d2dc1661679c63" method="get" name="search-form">
<input class="s-large" id="top-search-input-2" name="stext" placeholder="Buscar" size="20" tabindex="1" type="text" value=""/>
</form>
<div class="s-load fa-3x"><i class="far fa-spinner-third fa-spin"></i></div>
<i class="fal fa-times clear-search" style="display: none;"></i>
<div class="search-btn"><i class="fa-light fa-magnifying-glass"></i></div>
<div class="advsearch"><a href="https://www.filmaffinity.com/es/advsearch.php">Búsqueda avanzada <i class="fas fa-angle-double-right"></i></a></div>
</div><!-- topsearch -->
</div><!--search-box -->
<div id="user-login-container">
<div id="login-register">
<a class="sign-in" href="https://www.filmaffinity.com/es/login.php"><strong>Iniciar sesión</strong></a> / <a class="register" href="https://www.filmaffinity.com/es/register.php">Registrarse</a>
</div>
</div><!-- user-login -container -->
</div>
</div><!-- header-top -->
<div id="header-bottom">
<div class="cpanel news-wrapper">
<ul id="awardsmenu">
<li><a href="https://www.filmaffinity.com/es/topgen.php">Top FA</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/rankings.php">Rankings FA</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/calendar-tv.php">Calendario Series</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/category.php?id=TRAILERS">Tráilers</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/category.php?id=latest_reviews">Críticas</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/best_2025.php">2025</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/category.php?id=2026films">2026</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/all_awards.php">Premios</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/award-edition.php?edition-id=academy_awards_2026">Oscars™ <span class="tooltip-new">New</span></a></li><li class="sep">|</li>
</ul>
<div id="trmenu">
<div class="social-logo" id="tw-top-logo"><a href="https://twitter.com/Filmaffinity" rel="noopener noreferrer" target="_blank" title="Sigue a FA en Twitter (75.000 followers)"><i class="fa-brands fa-x-twitter"></i></a></div>
<div class="social-logo" id="in-top-logo"><a href="https://www.instagram.com/filmaffinity/" rel="noopener noreferrer" target="_blank" title="Sigue a FA en Instagram (155.000 followers)"><i class="fab fa-instagram"></i></a></div>

In [5]:
duracion = soup.find("div", class_='duration').get_text(strip=True)
duracion

'161 min.'

In [6]:
#TITULO
for i in soup.find_all("a", class_='d-none d-md-inline-block'):
    print(i.text)

Una batalla tras otra
Los pecadores
Rooster
Reversión
Weapons
DTF St. Louis
The Comeback
El caballero de los Siete Reinos
Love & Death
The Pitt
Superman
Mira: La vida después del divorcio
El infierno de las mujeres
Dune: Parte Dos
Portobello
Dune
Task
Yo, Rosinski
Singular
La acompañante
Barbie
Mickey 17
From
Succession
La empresa de sillas
El triángulo de la tristeza
La Casa del Dragón
Sobrevivir al Paraíso: Más allá de los Testigos de Jehová
Pubertat
El padre
Civil War
It: Bienvenidos a Derry
Primal
Red Eye
La ciudad es nuestra
Industry
Como agua para chocolate
Jurado Nº 2
Furia
Banksters

In [7]:
#DURACION
for i in soup.find_all("div", class_='duration'):
    print(i.get_text(strip=True))

161 min.
137 min.
35 min.
97 min.
128 min.
30 min.
30 min.
42 min.
55 min.
50 min.
119 min.
30 min.
45 min.
166 min.
60 min.
155 min.
65 min.
86 min.
100 min.
97 min.
114 min.
137 min.
50 min.
60 min.
30 min.
147 min.
60 min.
46 min.
45 min.
97 min.
109 min.
60 min.
22 min.
45 min.
60 min.
60 min.
50 min.
110 min.
35 min.
44 min.

In [8]:
#RANKING
for i in soup.find_all("div", class_='fa-list-position'):
    print(i.get_text(strip=True))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40

In [9]:
#RATING
for i in soup.find_all("div", class_='avg mx-0'):
    print(i.get_text(strip=True))

6,9
6,5
6,1
5,1
6,7
6,4
7,0
7,6
6,7
7,9
6,0
--
--
7,6
6,1
7,2
7,4
--
4,9
6,2
5,8
6,0
6,7
8,0
6,2
6,9
7,4
6,3
7,3
7,6
6,6
7,0
7,7
6,2
7,3
6,6
6,8
6,8
6,5
--

In [17]:
dict = {
    "titulo" : [],
    "año" : [],
    "duracion" : [],
    "posicion" : [],
    "rating" : []
}

In [18]:
# TODO  

#TITULO
for i in soup.find_all("a", class_='d-none d-md-inline-block'):
    titulo = i.text
    dict["titulo"].append(titulo)

#DURACION
for i in soup.find_all("div", class_='duration'):
    duracion = i.get_text(strip=True)
    dict["duracion"].append(duracion)

#RANKING
for i in soup.find_all("div", class_='fa-list-position'):
    posicion = i.get_text(strip=True)
    dict["posicion"].append(posicion)

#AÑO
for i in soup.find_all("span", class_='mc-year'):
    año = i.get_text(strip=True)
    dict["año"].append(año)

#RATING
for i in soup.find_all("div", class_='avg mx-0'):
    rating = i.get_text(strip=True)
    dict["rating"].append(rating)

In [19]:
dict
print(len(dict["titulo"]))
print(len(dict["año"]))
print(len(dict["posicion"]))
print(len(dict["duracion"]))
print(len(dict["rating"]))

40
40
40
40
40

In [20]:
import pandas as pd
df = pd.DataFrame(dict)
df

,titulo,año,duracion,posicion,rating
0,Una batalla tras otra,2025,161 min.,1,"6,9"
1,Los pecadores,2025,137 min.,2,"6,5"
2,Rooster,2026,35 min.,3,"6,1"
3,Reversión,2025,97 min.,4,"5,1"
4,Weapons,2025,128 min.,5,"6,7"
5,DTF St. Louis,2026,30 min.,6,"6,4"
6,The Comeback,2005,30 min.,7,"7,0"
7,El caballero de los Siete Reinos,2026,42 min.,8,"7,6"
8,Love & Death,2023,55 min.,9,"6,7"
9,The Pitt,2025,50 min.,10,"7,9"
10,Superman,2025,119 min.,11,"6,0"
11,Mira: La vida después del divorcio,2026,30 min.,12,--
12,El infierno de las mujeres,2026,45 min.,13,--
13,Dune: Parte Dos,2024,166 min.,14,"7,6"
14,Portobello,2026,60 min.,15,"6,1"
15,Dune,2021,155 min.,16,"7,2"
16,Task,2025,65 min.,17,"7,4"
17,"Yo, Rosinski",2024,86 min.,18,--
18,Singular,2025,100 min.,19,"4,9"
19,La acompañante,2025,97 min.,20,"6,2"
20,Barbie,2023,114 min.,21,"5,8"
21,Mickey 17,2025,137 min.,22,"6,0"
22,From,2022,50 min.,23,"6,7"
23,Succession,2018,60 min.,24,"8,0"
24,La empresa de sillas,2025,30 min.,25,"6,2"
25,El triángulo de la tristeza,2022,147 min.,26,"6,9"
26,La Casa del Dragón,2022,60 min.,27,"7,4"
27,Sobrevivir al Paraíso: Más allá de los Testigo...,2026,46 min.,28,"6,3"
28,Pubertat,2025,45 min.,29,"7,3"
29,El padre,2020,97 min.,30,"7,6"
30,Civil War,2024,109 min.,31,"6,6"
31,It: Bienvenidos a Derry,2025,60 min.,32,"7,0"
32,Primal,2019,22 min.,33,"7,7"
33,Red Eye,2024,45 min.,34,"6,2"
34,La ciudad es nuestra,2022,60 min.,35,"7,3"
35,Industry,2020,60 min.,36,"6,6"
36,Como agua para chocolate,2024,50 min.,37,"6,8"
37,Jurado Nº 2,2024,110 min.,38,"6,8"
38,Furia,2025,35 min.,39,"6,5"
39,Banksters,2026,44 min.,40,--

In [21]:
# código

df.to_csv("top25.csv")
df

,titulo,año,duracion,posicion,rating
0,Una batalla tras otra,2025,161 min.,1,"6,9"
1,Los pecadores,2025,137 min.,2,"6,5"
2,Rooster,2026,35 min.,3,"6,1"
3,Reversión,2025,97 min.,4,"5,1"
4,Weapons,2025,128 min.,5,"6,7"
5,DTF St. Louis,2026,30 min.,6,"6,4"
6,The Comeback,2005,30 min.,7,"7,0"
7,El caballero de los Siete Reinos,2026,42 min.,8,"7,6"
8,Love & Death,2023,55 min.,9,"6,7"
9,The Pitt,2025,50 min.,10,"7,9"
10,Superman,2025,119 min.,11,"6,0"
11,Mira: La vida después del divorcio,2026,30 min.,12,--
12,El infierno de las mujeres,2026,45 min.,13,--
13,Dune: Parte Dos,2024,166 min.,14,"7,6"
14,Portobello,2026,60 min.,15,"6,1"
15,Dune,2021,155 min.,16,"7,2"
16,Task,2025,65 min.,17,"7,4"
17,"Yo, Rosinski",2024,86 min.,18,--
18,Singular,2025,100 min.,19,"4,9"
19,La acompañante,2025,97 min.,20,"6,2"
20,Barbie,2023,114 min.,21,"5,8"
21,Mickey 17,2025,137 min.,22,"6,0"
22,From,2022,50 min.,23,"6,7"
23,Succession,2018,60 min.,24,"8,0"
24,La empresa de sillas,2025,30 min.,25,"6,2"
25,El triángulo de la tristeza,2022,147 min.,26,"6,9"
26,La Casa del Dragón,2022,60 min.,27,"7,4"
27,Sobrevivir al Paraíso: Más allá de los Testigo...,2026,46 min.,28,"6,3"
28,Pubertat,2025,45 min.,29,"7,3"
29,El padre,2020,97 min.,30,"7,6"
30,Civil War,2024,109 min.,31,"6,6"
31,It: Bienvenidos a Derry,2025,60 min.,32,"7,0"
32,Primal,2019,22 min.,33,"7,7"
33,Red Eye,2024,45 min.,34,"6,2"
34,La ciudad es nuestra,2022,60 min.,35,"7,3"
35,Industry,2020,60 min.,36,"6,6"
36,Como agua para chocolate,2024,50 min.,37,"6,8"
37,Jurado Nº 2,2024,110 min.,38,"6,8"
38,Furia,2025,35 min.,39,"6,5"
39,Banksters,2026,44 min.,40,--